yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: pnp
initFields:
  author:
    name: YOUR NAME
    url: "https://link-to-your-website.com"
  boilerplate:
    version: 2.2.6
    author: Chris Ferdinandi
    repo: "http://github.com/cferdinandi/gulp-boilerplate"
    url: "https://gomakethings.com"
  description: A description for your project.
  hint: "nodeLinker: pnp | node-modules"
  license: MIT
  main: ./dist/your-main-js-file.js
  name: project-name
  repository:
    type: git
    url: "https://link-to-your-git-repo.com"
  version": 1.0.0
